language: node_js
node_js:
  - "7"
script:
  - echo "Deploy!!"
install:
  - npm install -g firebase-tools
before_deploy: "npm run build"
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: empact-e511a
  skip_cleanup: true
