language: node_js
node_js:
  - "7"
script:
  - echo "Deploy!!"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project empact-e511a --token "1/qYKtoM3mB7O6XJutBL_BNEXSbWNTdsV1q4bTu4dG--fhcZZ3vzEcIpXH9jx1J-Jw"
