
import man from "./man.png";
import woman from "./woman.png";
import youth from "./youth.png";
import clinics from "./clinic2.png";
import emergency from "./emergency.png";
import hiv from "./hiv-aids.jpeg";
import mental from "./mental_health.jpg";
import rehab from "./rehab.png";
import pantry from "./food_pantry.png";
import stamps from "./food_stamps.png";
import bathroom from "./bathroom.png";
import shower from "./shower.png";
import afterSchool from "./after_school.png";
import abuse from "./abuse.png";
import socialServices from "./social_service.png";
import ged from "./GED.png";
import computers from "./computers.png";
import benefits from "./health_ins.png";